# SPDX-License-Identifier: GPL-3.0-only

# Set some default values
set(RINGWORLD_GIT_COMMIT_COUNT 0)
set(RINGWORLD_GIT_COMMIT "\"unknown\"")

# Set things whether or not things worked
if(${IN_GIT_REPO} STREQUAL "TRUE")
    execute_process(
        COMMAND "${GIT_EXECUTABLE}" --git-dir "${GIT_DIR}" rev-parse --short HEAD
        OUTPUT_VARIABLE RINGWORLD_GIT_COMMIT
    )
    execute_process(
        COMMAND "${GIT_EXECUTABLE}" --git-dir "${GIT_DIR}" rev-list --count HEAD
        OUTPUT_VARIABLE RINGWORLD_GIT_COMMIT_COUNT
    )
    string(STRIP "${RINGWORLD_GIT_COMMIT_COUNT}" RINGWORLD_GIT_COMMIT_COUNT)
    string(STRIP "${RINGWORLD_GIT_COMMIT}" RINGWORLD_GIT_COMMIT)
    set(RINGWORLD_FULL_VERSION_TEXT "${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}.${PROJECT_VERSION_PATCH}.r${RINGWORLD_GIT_COMMIT_COUNT}.${RINGWORLD_GIT_COMMIT}")
else()
    set(RINGWORLD_FULL_VERSION_TEXT "${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}.${PROJECT_VERSION_PATCH}.unknown")
endif()

# Overwrite version.hpp
file(WRITE "${OUT_FILE}" "#define RINGWORLD_VERSION_STRING \"${RINGWORLD_FULL_VERSION_TEXT}\"\n#define RINGWORLD_VERSION_MAJOR ${PROJECT_VERSION_MAJOR}\n#define RINGWORLD_VERSION_MINOR ${PROJECT_VERSION_MINOR}\n#define RINGWORLD_VERSION_PATCH ${PROJECT_VERSION_PATCH}\n#define RINGWORLD_GIT_COMMIT_COUNT ${RINGWORLD_GIT_COMMIT_COUNT}\n")
